version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: identityshelf
      POSTGRES_USER: identityshelf
      POSTGRES_PASSWORD: identityshelf
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U identityshelf"]
      interval: 10s
      timeout: 5s
      retries: 5

  admin-api:
    build:
      context: .
      dockerfile: services/admin-api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/identityshelf
      - SPRING_DATASOURCE_USERNAME=identityshelf
      - SPRING_DATASOURCE_PASSWORD=identityshelf
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  public-api:
    build:
      context: .
      dockerfile: services/public-api/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/identityshelf
      - SPRING_DATASOURCE_USERNAME=identityshelf
      - SPRING_DATASOURCE_PASSWORD=identityshelf
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  job-system:
    build:
      context: .
      dockerfile: services/job-system/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/identityshelf
      - SPRING_DATASOURCE_USERNAME=identityshelf
      - SPRING_DATASOURCE_PASSWORD=identityshelf
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  admin-frontend:
    build:
      context: admin-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - admin-api

volumes:
  postgres_data:
